<!-- Start Footer Section -->
      <div class="copyright-section">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <p>
                Copyright &copy; 2015 Span - Designed & Developed by
                <a href="http://graygrids.com">
                GrayGrids
                </a>
              </p>
            </div>
            <!-- .col-md-6 -->
            <div class="col-sm-6">
              <ul class="footer-nav">
                <li>
                  <a href="#">
                  Home /
                  </a>
                </li>
                <li>
                  <a href="#">
                  About Us /
                  </a>
                </li>
                <li>
                  <a href="#">
                  Privacy Police /
                  </a>
                </li>
                <li>
                  <a href="#">
                  Terms & Conditions /
                  </a>
                </li>
                <li>
                  <a href="#">
                  Support
                  </a>
                </li>
              </ul>
            </div>
            <!-- .col-md-6 -->
          </div>
          <!-- .row -->
        </div>
      </div>
      <!-- End Copyright -->
    </div>
    <!-- End Full Body Container -->
    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
    <i class="fa fa-angle-up">
    </i>
    </a>
    <div id="loader">
      <div class="ball-scale-multiple">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
    <!-- Span JS  -->
    <script type="text/javascript" src="assets/js/jquery-min.js"></script>
    <script type="text/javascript" src="assets/js/modernizrr.js"></script>
    <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="assets/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="assets/js/nivo-lightbox.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.mixitup.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.appear.js"></script>
    <script type="text/javascript" src="assets/js/count-to.js"></script>
    <script type="text/javascript" src="assets/js/jquery.parallax.js"></script>
    <script type="text/javascript" src="assets/js/smooth-scroll.js"></script>
    <script type="text/javascript" src="assets/js/jquery.slicknav.js"></script>
    <script type="text/javascript" src="assets/js/main.js"></script>
    <!-- Revelosition slider js -->
    <script src="assets/js/jquery.themepunch.revolution.min.js"></script>
    <script src="assets/js/jquery.themepunch.tools.min.js"></script>
  </body>
</html>
