<?php
include_once "config.php";
include_once ROOT.DS."controllers".DS."menuController.php";
include_once ROOT.DS."controllers".DS."magazinesController.php";
$nav = new magazinesController();
$sector = $nav->getNavlevel0();
//var_dump($sector);
$url =($_SERVER['REQUEST_URI']);
$page = explode('/', $url);
 ?>
<div class="navbar navbar-default navbar-top">
          <div class="container">
            <div class="navbar-header">
              <!-- Stat Toggle Nav Link For Mobiles -->
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <i class="fa fa-bars">
              </i>
              </button>
              <!-- End Toggle Nav Link For Mobiles -->
              <a class="navbar-brand" href="/index.php">
              <img alt="" src="/assets/img/logo-edpsante.png">
              </a>
            </div>
            <div class="navbar-collapse collapse">
              <!-- Stat Search -->
              <div class="search-side">
                <a class="show-search">
                <i class="fa fa-search"></i>
                </a>
              </div>
              <!-- Form for navbar search area -->
              <form class="full-search">
                <div class="container">
                  <div class="row">
                    <input class="form-control" type="text" placeholder="Type to Search">
                    <a class="close-search">
                    <span class="fa fa-times fa-2x">
                    </span>
                    </a>
                  </div>
                </div>
              </form>
              <!-- Search form ends -->
              <!-- Start Navigation List -->
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <?= ($page[1] == "/index.php") ?  "<a href='/index.php' class='active'>" :  "<a href='/index.php'>";?>
                  Home
                  </a>
                </li>
                <li>

                  <?= (substr_compare($page[1],"single-project.php",0,10) === 0) ?  "<a href='#' class='active'>" :  "<a href='#'>";?>
                    Nos magazines
                  </a>
                  <ul class="dropdown">
                    <?php $i = 0;?>
                    <?php foreach ($sector as $pole => $value):?>
                    <li>

                      <a href="#">
                      <?php echo $nav->getNavLevel0Name($i)?>
                      </a>
                      <?php $magazine = $nav->getNavLevel1($i)?>
                      <ul class="sup-dropdown">

                        <?php foreach ($magazine as $key => $value): ?>
                  <?php usort($magazine,function($a,$b) {return strnatcasecmp($a->name,$b->name);}); ?>
                        <?php $title = $nav->getMagazineInfos($pole,$key) ?>
                        <li>
                          <a href="http://edp-sante.fr/magazine/<?=$pole?><?=$key?>-<?= $title->url?>">
                            <?= $nav->getNavLevel1Name($i,$key)?>
                          </a>
                        </li>
                        <?php endforeach; ?>
                      </ul>
                    </li>
                    <?php $i++; endforeach ?>
                  </ul>
                <li>
                  <?= ($page[1] == "/about.php") ?  "<a href='/about.php' class='active'>" :  "<a href='/about.php'>";?>
                  Nos services
                  </a>
                </li>
                <li>
                  <?= ($page[1] == "/contact.php") ?  "<a href='/contact.php' class='active'>" :  "<a href='/contact.php'>";?>
                  Contact
                  </a>
                </li>
              </ul>
              <!-- End Navigation List -->
            </div>
          </div>

          <!-- Mobile Menu Start -->
          <ul class="wpb-mobile-menu">
            <li>
              <?= ($page[1] == "index.php") ?  "<a href='index.php' class='active'>" :  "<a href='index.php'>";?>
              Home
              </a>
            </li>
            <li>
              <?= (substr_compare($page[1],"single-project.php",0,10) === 0) ?  "<a href='#' class='active'>" :  "<a href='#'>";?>
                Nos magazines
              </a>
              <ul class="dropdown">
                  <?php $i = 0;?>
                    <?php foreach ($sector as $pole => $value):?>
                    <li>

                      <a href="#">
                      <?php echo $nav->getNavLevel0Name($i)?>
                      </a>
                      <?php $magazine = $nav->getNavLevel1($i)?>
                      <ul class="sup-dropdown">
                        <?php foreach ($magazine as $key => $value): ?>
                        <li>
                          <a href="http://edp-sante.fr/magazine/<?=$pole?><?=$key?>-<?= $title->url?>">
                            <?= $nav->getNavLevel1Name($i,$key)?>
                          </a>
                        </li>
                        <?php endforeach; ?>
                      </ul>
                    </li>
                    <?php $i++; endforeach ?>
              </ul>
            </li>
            <li>
              <?= ($page[3] == "contact.php") ?  "<a href='contact.php' class='active'>" :  "<a href='contact.php'>";?>
                Contact
              </a>
            </li>
          </ul>
          <!-- Mobile Menu End -->

        </div>
        <!-- End Header Logo & Naviagtion -->
      </header>
      <!-- End Header Section -->
