  <body style="background-image: url("http://localhost/Portail-EDP-Sante/span-template/assets/img/patterns/3.png");">
    <!-- Full Body Container -->
    <div id="container" class="boxed-page">
      <!-- Start Header Section -->
      <div class="hidden-header">
      </div>
      <header class="clearfix">
        <!-- Start Top Bar -->
        <div class="top-bar">
          <div class="container">
            <div class="row">
              <div class="col-md-7 col-sm-9">
                <!-- Start Contact Info -->
                <ul class="contact-details">
                  <li>
                    <a href="#">
                    <i class="icon-pointer">
                    </i>
                    New South wales, Sydaney
                    </a>
                  </li>
                  <li>
                    <a href="#">
                    <i class="icon-call-out">
                    </i>
                    Call Us: (123) 456- 789
                    </a>
                  </li>
                  <li>
                    <a href="#">
                    <i class="icon-envelope">
                    </i>
                    Email@example.com
                    </a>
                  </li>
                </ul>
                <!-- End Contact Info -->
              </div>
              <div class="col-md-5 col-sm-3">
                <!-- Start Social Links -->
                <ul class="social-list">
                  <li>
                    <a class="facebook itl-tooltip" data-placement="bottom" title="Facebook" href="#">
                    <i class="fa fa-facebook">
                    </i>
                    </a>
                  </li>
                  <li>
                    <a class="twitter itl-tooltip" data-placement="bottom" title="Twitter" href="#">
                    <i class="fa fa-twitter">
                    </i>
                    </a>
                  </li>
                  <li>
                    <a class="google itl-tooltip" data-placement="bottom" title="Google Plus" href="#">
                    <i class="fa fa-google-plus">
                    </i>
                    </a>
                  </li>
                  <li>
                    <a class="dribbble itl-tooltip" data-placement="bottom" title="Dribble" href="#">
                    <i class="fa fa-dribbble">
                    </i>
                    </a>
                  </li>
                  <li>
                    <a class="linkdin itl-tooltip" data-placement="bottom" title="Linkedin" href="#">
                    <i class="fa fa-linkedin">
                    </i>
                    </a>
                  </li>
                </ul>
                <!-- End Social Links -->
              </div>
            </div>
          </div>
        </div>
        <!-- End Top Bar -->
        <!-- Start  Logo & Naviagtion  -->
  
